/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: the_goobadooba (https://sketchfab.com/the_goobadooba)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crossy-road-godzilla-a67b494f30c445c0be8cb7d6b8484174
title: Crossy road godzilla
*/

import React, { useEffect, useRef } from 'react'
import {
  useGLTF,
  useAnimations,
  Merged,
  Clone,
  useScroll,
} from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Characters() {
  const scroll = useScroll()
  const ref = useRef()
  const { nodes, materials, animations, scene } = useGLTF(
    '/models/crossy_road_godzilla.glb'
  )

  useFrame((state) => {
    ref.current.position.z = -(scroll.offset - 0.5) * 40
  })

  const { actions } = useAnimations(animations, ref)

  return (
    <group ref={ref}>
      {Array(40)
        .fill(0)
        .map((_, i) => (
          <CrossyRoadGodzilla
            key={i}
            position={[
              (Math.random() - 0.5) * 40,
              0,
              (Math.random() - 0.5) * 40 + 10,
            ]}
          />
        ))}
    </group>
  )
}

export function CrossyRoadGodzilla(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    '/models/crossy_road_godzilla.glb'
  )
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['animation.crossy road godzilla.new'].play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group name='_44'>
                <group name='leg2_17' position={[0.31, 0.44, 0]}>
                  <group name='cube_11' position={[0.5, -0.44, 0]}>
                    <mesh
                      name='Object_28'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_28.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_12' position={[0.5, -0.44, 0]}>
                    <mesh
                      name='Object_30'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_30.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_13' position={[0.5, -0.44, 0]}>
                    <mesh
                      name='Object_32'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_32.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_14' position={[0.5, -0.44, 0]}>
                    <mesh
                      name='Object_34'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_34.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_15' position={[0.5, -0.44, 0]}>
                    <mesh
                      name='Object_36'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_36.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_16' position={[0.5, -0.44, 0]}>
                    <mesh
                      name='Object_38'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_38.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name='leg_24' position={[-0.31, 0.5, 0]}>
                  <group name='cube_18' position={[0.31, -0.5, 0]}>
                    <mesh
                      name='Object_41'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_41.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_19' position={[0.31, -0.5, 0]}>
                    <mesh
                      name='Object_43'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_43.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_20' position={[0.31, -0.5, 0]}>
                    <mesh
                      name='Object_45'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_45.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_21' position={[0.31, -0.5, 0]}>
                    <mesh
                      name='Object_47'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_47.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_22' position={[0.31, -0.5, 0]}>
                    <mesh
                      name='Object_49'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_49.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_23' position={[0.31, -0.5, 0]}>
                    <mesh
                      name='Object_51'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_51.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name='head_43' position={[0, 1.19, 0]}>
                  <group name='cube_35' position={[0, -1.18, -0.1]}>
                    <mesh
                      name='Object_68'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_68.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_36' position={[0, -1.18, -0.1]}>
                    <mesh
                      name='Object_70'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_70.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_37' position={[0, -1.18, -0.1]}>
                    <mesh
                      name='Object_72'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_72.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_38' position={[0, -1.18, -0.1]}>
                    <mesh
                      name='Object_74'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_74.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_39' position={[0, -1.18, -0.1]}>
                    <mesh
                      name='Object_76'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_76.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_40' position={[0, -1.18, -0.1]}>
                    <mesh
                      name='Object_78'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_78.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_41' position={[0, -1.18, -0.1]}>
                    <mesh
                      name='Object_80'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_80.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_42' position={[0, -1.19, 0]}>
                    <mesh
                      name='Object_82'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_82.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name='cube_0'>
                  <mesh
                    name='Object_5'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_1'>
                  <mesh
                    name='Object_7'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_2'>
                  <mesh
                    name='Object_9'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_3'>
                  <mesh
                    name='Object_11'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_4'>
                  <mesh
                    name='Object_13'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_5'>
                  <mesh
                    name='Object_15'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_6'>
                  <mesh
                    name='Object_17'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_7'>
                  <mesh
                    name='Object_19'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_8'>
                  <mesh
                    name='Object_21'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_9'>
                  <mesh
                    name='Object_23'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='cube_10'>
                  <mesh
                    name='Object_25'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name='bone_28'>
                  <group name='cube_25'>
                    <mesh
                      name='Object_54'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_54.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_26'>
                    <mesh
                      name='Object_56'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_56.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_27'>
                    <mesh
                      name='Object_58'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_58.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name='bone2_33' position={[0.75, 0, 0]}>
                  <group name='cube_30'>
                    <mesh
                      name='Object_61'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_61.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_31'>
                    <mesh
                      name='Object_63'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_63.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name='cube_32'>
                    <mesh
                      name='Object_65'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_65.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/crossy_road_godzilla.glb')
